name = "codust-dev-website"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "8ceb2100fa1ed04117c9e5d43b5f5743"

[site]
bucket = ".next"

[env.production]
name = "codust-dev-website"
route = "codust.dev/*"
zone_id = "your-zone-id"

[env.preview]
name = "codust-dev-website-preview"
route = "preview.codust.dev/*"
zone_id = "your-zone-id" 