[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".next"
entry-point = "."

[env.production]
name = "codust-dev"
route = "codust.dev/*"
zone_id = "your-zone-id"

[env.preview]
name = "codust-dev-preview"
route = "preview.codust.dev/*"
zone_id = "your-zone-id" 